# Generated by Django 4.2.6 on 2024-01-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0025_alter_course_id_alter_courseinfo_id_alter_section_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='passing_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.grade'),
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.ugmajor'),
        ),
        migrations.AlterField(
            model_name='subjectchoice',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.course'),
        ),
        migrations.AlterField(
            model_name='subjectchoice',
            name='subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.subjectcode'),
        ),
    ]
