# Generated by Django 4.2.6 on 2024-01-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0026_alter_course_passing_grade_alter_course_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectcode',
            options={'verbose_name': 'Subject abbr', 'verbose_name_plural': 'Subject abbrs'},
        ),
        migrations.AlterModelOptions(
            name='subjectlevel',
            options={'verbose_name': 'Subject code', 'verbose_name_plural': 'Subject codes'},
        ),
    ]
