# Generated by Django 4.2.6 on 2024-01-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0027_alter_subjectcode_options_alter_subjectlevel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectlevel',
            name='level',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
