# Generated by Django 4.2.6 on 2024-01-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0028_alter_subjectlevel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
