# Generated by Django 4.2.6 on 2024-01-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0029_section_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['priority']},
        ),
    ]
