# Generated by Django 4.2.6 on 2024-01-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0030_alter_section_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-priority']},
        ),
    ]
