# Generated by Django 4.2.6 on 2024-01-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0031_alter_section_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ugmajor',
            options={'ordering': ['-priority']},
        ),
        migrations.AddField(
            model_name='ugmajor',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
