# Generated by Django 4.2.6 on 2024-01-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0032_alter_ugmajor_options_ugmajor_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditOption',
            fields=[
                ('value', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'da_credit_option',
            },
        ),
    ]
