# Generated by Django 4.2.6 on 2024-01-31 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0033_creditoption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditoption',
            options={'ordering': ['-value']},
        ),
    ]
