# Generated by Django 4.2.6 on 2024-01-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0035_alter_creditoption_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectchoice',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
