# Generated by Django 4.2.6 on 2024-01-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0036_subjectchoice_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectchoice',
            name='is_free',
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
