# Generated by Django 4.2.6 on 2024-01-31 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0037_remove_subjectchoice_is_free_course_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='adviser',
        ),
    ]
